### PR TITLE
Change constraint min operating point, and its test and doc

### PR DESCRIPTION
**Pull request by gnawin**
The constraint minimum operating point and its test and documentation on the math formulation have been changed.

It closes part of #654. 

## Checklist before merging
- [x] Documentation is up-to-date
- [x] Unit tests have been added/updated accordingly
- [x] Code has been formatted according to SpineOpt's style
- [x] Unit tests pass

### CODE REVIEW

**Comment by gnawin** [comment]
Hi @mihlema @DillonJ, I think this change is interesting for you, so I requested you both as reviewers. Would you please have a look? Feel free to propose others in place/additional as well. Thanks!

**Comment by manuelma** [comment]
I propose I review this.

@gnawin would it be possible to describe the change in words? What changed in the constraint and why?

**Comment by manuelma** [comment]
I think I get the idea. 
Before the constraint was, roughly:

```
unit_flow >= min_op_point * units_on
```

And now it is, again, roughly:
```
normal_unit_flow - downward_reserve_unit_flow >= min_op_point * (units_on - units_hold_for_downward_reserve_provision)
```

Which makes sense to me. So we don't count the downward reserve provision for the purposes of imposing the unit's minimum operating point.

Is that about right @gnawin ?

**Comment by gnawin** [comment]
> I think I get the idea. Before the constraint was, roughly:
> 
> ```
> unit_flow >= min_op_point * capacity * units_on
> ```
> 
> And now it is, again, roughly:
> 
> ```
> normal_unit_flow - downward_reserve_unit_flow >= min_op_point * capacity * (units_on - units_held_for_downward_reserve_provision)
> ```
> 
> Which makes sense to me. So we don't count the downward reserve provision for the purposes of imposing the unit's minimum operating point.
> 
> Is that about right @gnawin ?

Yes, that's basically the idea. See more information below.

The new formulation is given in the documentation within this PR. 

Major change 1:
The indices of the constraint remain the same, but a few terms on both the LHS and the RHS have been added. 
On the LHS, besides the flows for the non-reserves, the flows for the reserves (downward spinning and non-spinning) has been substracted. 
On the RHS, the unit committed to the non-spinning reserve has been substracted for the units on.

Major change 2:
On the LHS, `duration(t)` was outside the sume of `unit_flow`. This was wrong because in case of different time resolution for `unit_flow`, `duration(t)` has to be inside the sum as well. 

Question:  
However, the t_indices may need to be changed, see #763.

The unit tests has been modified, and written in a way that reflects the major change 2.

**Comment by DillonJ** [comment]
Questions @manuelma if I don't have any reserves defined, does this add new variables to the problem that aren't needed?

**Comment by manuelma** [comment]
> Questions @manuelma if I don't have any reserves defined, does this add new variables to the problem that aren't needed?

Good question @DillonJ - no, it doesn't. This PR is very slim, it doesn't change anything related to variable generation - just adds a couple of extra terms in one constraint.

**Comment by manuelma** [comment]
Nice work @gnawin !

**Pull request merged**
